name: job execution testing

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job1 step
        run: echo "this is job1 running"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: job2 step
        run: echo "this is job2 running"
